site_name: Provide Foundation Documentation
site_description: Beautiful, Performant, Structured Logging for Python - Enterprise-grade telemetry built on structlog
site_author: provide.io
site_url: https://foundry.provide.io/foundation/
repo_url: https://github.com/provide-io/provide-foundation
repo_name: provide-io/provide-foundation
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024-2025 provide.io

# Development server configuration
dev_addr: '127.0.0.1:8001'

# Standalone mode settings
docs_dir: docs

theme:
  name: material
  language: en
  logo: assets/images/officium-light.svg
  favicon: assets/images/officium-light.svg

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - navigation.top
    - header.autohide
    - content.code.copy
    - content.tabs.link

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_signature_annotations: true
            show_bases: true
            merge_init_into_class: true
            separate_signature: true

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js

nav:
  - Home: index.md

  - Information:
    - Features: information/features.md
    - Use Cases: information/use-cases.md
    - Architecture: information/architecture.md
    - Changelog: information/changelog.md

  - Getting Started:
    - getting-started/index.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - First Application: getting-started/first-app.md
    - Examples: getting-started/examples.md

  - Tutorials:
    - Quick Start: tutorials/01-quick-start.md
    - First Application: tutorials/02-first-app.md

  - How-To Guides:
    - Logging:
      - Basic Logging: how-to-guides/logging/basic-logging.md
      - Exception Logging: how-to-guides/logging/exception-logging.md
    - CLI:
      - Commands: how-to-guides/cli/commands.md
    - Resilience:
      - Retry Patterns: how-to-guides/resilience/retry.md

  - Explanation:
    - Architecture: explanation/architecture.md
    - Dependency Injection: explanation/dependency-injection.md

  - Reference:
    - API Reference: reference/index.md

  - Specs: specs/index.md
