site_name: Provide Foundation Documentation
site_description: Beautiful, Performant, Structured Logging for Python - Enterprise-grade telemetry built on structlog
site_author: provide.io
site_url: https://foundation.provide.io
repo_url: https://github.com/provide-io/provide-foundation
repo_name: provide-io/provide-foundation
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024-2025 provide.io
docs_dir: docs

theme:
  name: material
  language: en
  custom_dir: overrides
  logo: assets/images/logo.svg
  favicon: assets/images/logo.svg
  
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  font:
    text: Poppins
    code: Fira Code
  
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - navigation.top
    - header.autohide
    - content.code.copy
    - content.tabs.link

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: false
            show_root_heading: true

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js

nav:
  - Information:
    - Overview: index.md
    - Features: information/features.md
    - Use Cases: information/use-cases.md
    - Architecture: information/architecture.md
    - Changelog: information/changelog.md
  
  - Getting Started:
    - getting-started/index.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - First Application: getting-started/first-app.md
    - Examples: getting-started/examples.md

  - Guide:
    - guide/index.md
    - Core Concepts:
      - guide/concepts/index.md
      - Structured Logging: guide/concepts/structured-logging.md
      - Emoji Sets: guide/concepts/emoji-sets.md
      - Emoji System: guide/concepts/emoji-system.md
      - Domain-Action-Status Pattern: guide/concepts/das-pattern.md
      - Performance: guide/concepts/performance.md
    - Configuration:
      - guide/config/index.md
      - Environment Variables: guide/config/environment.md
      - Config Files: guide/config/files.md
      - Runtime Config: guide/config/runtime.md
      - Best Practices: guide/config/best-practices.md
    - Logging:
      - Basic Usage: guide/logging/basic.md
      - Advanced Patterns: guide/logging/advanced.md
      - Async Logging: guide/logging/async.md
      - Exception Handling: guide/logging/exceptions.md
      - Context Management: guide/logging/context.md
      - Performance Tuning: guide/logging/performance.md
    - CLI Framework:
      - guide/cli/index.md

  - Reference:
    - api/index.md
    - Logger API: api/logger/index.md
    - Configuration API: api/config/index.md
    - Context API: api/context/index.md
    - CLI API: api/cli/index.md
    - Hub API: api/hub/index.md
    - File API: api/file/index.md
    - Crypto API: api/crypto/index.md
    - Console API: api/utils/console.md
    - Utils API: api/utils/index.md

  - Contributing:
    - development/index.md
    - Contributing: development/contributing.md
    - CI/CD: development/ci-cd.md
