# MkDocs Configuration
# For a full reference, see https://www.mkdocs.org/user-guide/configuration/
# For Material theme options, see https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/

site_name: provide.foundation
site_description: 'Beautiful, Performant, Structured Logging for Python'
site_author: Provide

repo_url: https://github.com/provide-io/provide-foundation
repo_name: provide-io/provide-foundation

# Copyright
copyright: 'Copyright &copy; 2017 - 2025 Provide'

# Theme Configuration
theme:
  name: material
  logo: assets/logo.svg # You may need to create this file
  favicon: assets/favicon.ico # You may need to create this file
  language: en

  # Features for a top-tier experience
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.tabs.link

  # Color Palette (with light/dark mode toggle)
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Features for a top-tier experience
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.tabs.link

  # Color Palette (with light/dark mode toggle)
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugins
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: yes
            show_source: false
            docstring_style: google
            heading_level: 3
            show_signature_annotations: true
            separate_signature: true

# Markdown Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

# Navigation Structure
nav:
  - 'Home': 'index.md'
  - 'Getting Started':
    - 'Installation': 'getting-started/installation.md'
    - 'Quick Start': 'getting-started/quick-start.md'
  - 'Core Concepts':
    - 'Structured Logging': 'core-concepts/structured-logging.md'
    - 'Semantic Layers': 'core-concepts/semantic-layers.md'
    - 'The Emoji System': 'core-concepts/emoji-system.md'
    - 'Configuration': 'core-concepts/configuration.md'
    - 'Architecture': 'core-concepts/architecture.md'
  - 'Guides':
    - 'Async Usage': 'guides/async-usage.md'
    - 'Exception Logging': 'guides/exception-logging.md'
    - 'Performance Tuning': 'guides/performance-tuning.md'
    - 'Custom Semantic Layers': 'guides/creating-semantic-layers.md'
  - 'API Reference':
    - 'Logger': 'api-reference/logger.md'
    - 'Configuration': 'api-reference/config.md'
    - 'Semantic Layers': 'api-reference/semantic-layers.md'
    - 'Error Handling': 'api-reference/errors.md'
    - 'Utilities': 'api-reference/utils.md'
    - 'Hub': 'api-reference/hub.md'
  - 'About':
    - 'Contributing': 'about/contributing.md'
    - 'License': 'LICENSE' # Link to existing license file
