site_name: provide.foundation Documentation
site_description: Beautiful, Performant, Structured Logging for Python - Enterprise-grade telemetry built on structlog
site_author: provide.io
site_url: https://foundation.provide.io
repo_url: https://github.com/provide-io/provide-foundation
repo_name: provide-io/provide-foundation
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024-2025 provide.io

theme:
  name: material
  language: en
  
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  font:
    text: Inter
    code: Fira Code
  
  features:
    # Navigation
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.prune
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    
    # Table of contents
    - toc.follow
    - toc.integrate
    
    # Search
    - search.suggest
    - search.highlight
    - search.share
    
    # Content
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view
    
    # Header
    - header.autohide
    
    # Announce
    - announce.dismiss

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - en
  
  - autorefs
  
  
  - section-index
  

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - meta
  
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic:
      mode: view
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: provide-io
      repo: provide-foundation

extra:
  version:
    provider: mike
    default: latest
  
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/provide-io/provide-foundation
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/provide-foundation/
    - icon: fontawesome/solid/globe
      link: https://provide.io
  
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

extra:
  mermaid:
    enabled: true

nav:
  - Home: index.md
  
  - Getting Started:
    - getting-started/index.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - First Application: getting-started/first-app.md
    - Examples: getting-started/examples.md
  
  - User Guide:
    - guide/index.md
    - Core Concepts:
      - guide/concepts/index.md
      - Structured Logging: guide/concepts/structured-logging.md
      - Semantic Layers: guide/concepts/semantic-layers.md
      - Emoji System: guide/concepts/emoji-system.md
      - Domain-Action-Status: guide/concepts/das-pattern.md
      - Performance: guide/concepts/performance.md
    
    - Config:
      - guide/config/index.md
      - Environment Variables: guide/config/environment.md
      - Config Files: guide/config/files.md
      - Runtime Config: guide/config/runtime.md
      - Best Practices: guide/config/best-practices.md
    
    - Logging:
      - guide/logging/index.md
      - Basic Usage: guide/logging/basic.md
      - Advanced Patterns: guide/logging/advanced.md
      - Async Logging: guide/logging/async.md
      - Exception Handling: guide/logging/exceptions.md
      - Context Management: guide/logging/context.md
      - Performance Tuning: guide/logging/performance.md
    
    - CLI Framework:
      - guide/cli/index.md
      - Command Registration: guide/cli/commands.md
      - Nested Commands: guide/cli/nested.md
      - Arguments & Options: guide/cli/arguments.md
      - Output Formatting: guide/cli/output.md
      - Testing CLI Apps: guide/cli/testing.md
    
    - System Utilities:
      - guide/utilities/index.md
      - Platform Detection: guide/utilities/platform.md
      - Process Execution: guide/utilities/process.md
      - Console Output: guide/utilities/console.md
      - Registry Pattern: guide/utilities/registry.md
      - Error Handling: guide/utilities/errors.md
  
  
  - API Reference:
    - api/index.md
    - Logger:
      - api/logger/index.md
      - Base Logger: api/logger/base.md
      - Configuration: api/logger/config.md
      - Processors: api/logger/processors.md
      - Emoji Matrix: api/logger/emoji.md
    
    - Configuration:
      - api/config/index.md
      - Config Manager: api/config/manager.md
      - Environment: api/config/env.md
      - Loaders: api/config/loader.md
      - Schema: api/config/schema.md
    
    - CLI:
      - api/cli/index.md
      - Decorators: api/cli/decorators.md
      - Testing: api/cli/testing.md
      - Utilities: api/cli/utils.md
    
    - Hub:
      - api/hub/index.md
      - Components: api/hub/components.md
      - Registry: api/hub/registry.md
      - Commands: api/hub/commands.md
    
    - Utilities:
      - api/utils/index.md
      - Platform: api/platform/index.md
      - Process: api/process/index.md
      - File Operations: api/file/index.md
      - Crypto: api/crypto/index.md
      - Errors: api/errors/index.md

  - Cookbook:
    - cookbook/index.md
    - Recipes:
      - cookbook/recipes/index.md
      - FastAPI Integration: cookbook/recipes/fastapi.md
      - Django Integration: cookbook/recipes/django.md
      - Flask Integration: cookbook/recipes/flask.md
      - Celery Tasks: cookbook/recipes/celery.md
      - Docker Logging: cookbook/recipes/docker.md
      - Kubernetes Logging: cookbook/recipes/kubernetes.md
      - CI/CD Pipelines: cookbook/recipes/ci-cd.md
      - Testing Strategies: cookbook/recipes/testing.md
    
    - Examples:
      - cookbook/examples/index.md
      - Web Applications: cookbook/examples/web-app.md
      - CLI Tools: cookbook/examples/cli-tool.md
      - Data Pipelines: cookbook/examples/data-pipeline.md
      - Microservices: cookbook/examples/microservices.md
      - Machine Learning: cookbook/examples/ml-logging.md
      - Async Services: cookbook/examples/async-services.md
    
    - Patterns:
      - cookbook/patterns/index.md
      - Error Boundaries: cookbook/patterns/error-boundaries.md
      - Context Propagation: cookbook/patterns/context.md
      - Request Tracing: cookbook/patterns/tracing.md
      - Performance Monitoring: cookbook/patterns/monitoring.md
      - Audit Logging: cookbook/patterns/audit.md
  
  - Tutorials:
    - tutorials/index.md
    - Building a CLI App: tutorials/cli-application.md
    - FastAPI with Telemetry: tutorials/fastapi-integration.md
    - Custom Semantic Layer: tutorials/custom-semantic-layer.md
    - Production Logging: tutorials/production-logging.md
    - Distributed Tracing: tutorials/distributed-tracing.md
  
  - Development:
    - development/index.md
    - Contributing: development/contributing.md
    - Architecture: development/architecture.md
    - Testing:
      - development/testing/index.md
      - Unit Tests: development/testing/unit.md
      - Integration Tests: development/testing/integration.md
      - Performance Tests: development/testing/performance.md
      - Coverage Reports: development/testing/coverage.md
    - CI/CD: development/ci-cd.md
    - Release Process: development/release.md
    - Roadmap: development/roadmap.md
  
  - Architecture & Design:
    - architecture/index.md
    - Telemetry Format: architecture/telemetry-format.md
    - Semantic Layer Design: architecture/semantic-layers.md
    - Emoji System: architecture/emoji-system.md
    - Performance: architecture/performance.md
    - Design Decisions:
      - architecture/decisions/index.md
      - Semantic Layers: architecture/decisions/semantic-layers.md
      - Async Support: architecture/decisions/async-support.md
      - Plugin System: architecture/decisions/plugins.md
      - Distributed Tracing: architecture/decisions/tracing.md
      - Metrics Integration: architecture/decisions/metrics.md
  
  - Troubleshooting:
    - troubleshooting/index.md
    - Common Issues: troubleshooting/common.md
    - Platform-Specific:
      - troubleshooting/platforms/index.md
      - macOS: troubleshooting/platforms/macos.md
      - Linux: troubleshooting/platforms/linux.md
      - Windows: troubleshooting/platforms/windows.md
      - Docker: troubleshooting/platforms/docker.md
    - Performance Issues: troubleshooting/performance.md
    - Configuration Problems: troubleshooting/configuration.md
    - Error Messages: troubleshooting/errors.md
    - FAQ: troubleshooting/faq.md
  
  - Migration:
    - migration/index.md
    - From structlog: migration/from-structlog.md
    - From logging: migration/from-logging.md
    - From pyvider: migration/from-pyvider.md
    - API Changes: migration/api-changes.md
  
  - Community:
    - community/index.md
    - Support: community/support.md
    - Discussions: community/discussions.md
    - Blog: community/blog.md
    - Showcase: community/showcase.md

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

watch:
  - src/provide
  - docs
  - mkdocs.yml