name: 📚 Documentation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'README.md'
      - 'docs/**'
      - 'examples/**'
  pull_request:
    paths:
      - 'README.md'
      - 'docs/**'
      - 'examples/**'
  workflow_dispatch:

env:
  UV_VERSION: "0.7.8"

jobs:
  docs:
    name: 📚 Documentation Validation
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🐍 Setup Python ${{ matrix.os }}-${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.os }}-${{ matrix.python-version }}

      - name: ⚡ Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: ${{ env.UV_VERSION }}

      - name: 📦 Install Dependencies
        run: |
          uv sync --all-groups

      - name: 📖 Test Example Scripts
        run: |
          source env.sh
          for example in examples/*.py; do
              python ${example}
          done

      - name: 🔗 Validate README Links
        run: |
          # Install markdown link checker
          npm install -g markdown-link-check
          markdown-link-check README.md --config .github/markdown-link-check.json
        continue-on-error: true
